// Generated by CoffeeScript 1.9.1
Template.navbar.events({
  'click #resetdb': function(event) {
    console.log("About to reset the db");
    return Meteor.call('resetdb', function(error, result) {
      return Console.log("client called Meteor.resetdb: " + result);
    });
  }
});
